version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - 8082:8080
    volumes:
      - .:/app



